tap "dopplerhq/cli"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "openssl@1.1"
brew "gettext"
brew "awscli"
brew "fzf"
brew "go"
brew "libdvdcss"
brew "libyaml"
brew "luarocks"
brew "mkvtoolnix"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "rustup-init"
brew "tmux"
brew "yarn"
brew "dopplerhq/cli/doppler"
brew "heroku/brew/heroku", link: false
cask "iterm2"
cask "makemkv"
cask "metaz"
